INSERT INTO GENERO VALUES ('1', 'Acción')
INSERT INTO GENERO VALUES ('2', 'Comedia')
INSERT INTO GENERO VALUES ('3', 'Terror')
INSERT INTO GENERO VALUES ('4', 'Drama')
INSERT INTO GENERO VALUES ('5', 'Ciencia Ficción')
INSERT INTO GENERO VALUES ('6', 'Romance')
INSERT INTO GENERO VALUES ('7', 'Aventura')
INSERT INTO GENERO VALUES ('8', 'Suspenso')
INSERT INTO GENERO VALUES ('9', 'Animación')
INSERT INTO GENERO VALUES ('10', 'Documental')



INSERT INTO DISTRIBUIDOR VALUES ('1', 'Warner Bros','contacto@warner.com')
INSERT INTO DISTRIBUIDOR VALUES ('2', 'Paramount','contacto@paramount.com')
INSERT INTO DISTRIBUIDOR VALUES ('3', 'Universal Pictures','info@universal.com')
INSERT INTO DISTRIBUIDOR VALUES ('4', 'Sony Pictures','contacto@sony.com')
INSERT INTO DISTRIBUIDOR VALUES ('5', '20th Century Studios','info@20thcentury.com')
INSERT INTO DISTRIBUIDOR VALUES ('6', 'Lionsgate','contacto@lionsgate.com')
INSERT INTO DISTRIBUIDOR VALUES ('7', 'Netflix Studios','studio@netflix.com')
INSERT INTO DISTRIBUIDOR VALUES ('8', 'Amazon Studios','contacto@amazonstudios.com')
INSERT INTO DISTRIBUIDOR VALUES ('9', 'Walt Disney Studios','contacto@disney.com')
INSERT INTO DISTRIBUIDOR VALUES ('10', 'Illumination','info@illumination.com')


INSERT INTO PELICULA VALUES ('1', '120','PG-13','Batman', '1','1')
INSERT INTO PELICULA VALUES ('2', '95','PG','Sonic', '2','2')
INSERT INTO PELICULA VALUES ('3', '110','R','El Conjuro', '3','3')
INSERT INTO PELICULA VALUES ('4', '150','PG-13','Inception', '4','5')
INSERT INTO PELICULA VALUES ('5', '130','PG','Titanic', '2','4')
INSERT INTO PELICULA VALUES ('6', '102','PG','Minions', '10','9')
INSERT INTO PELICULA VALUES ('7', '140','PG-13','Avengers', '9','1')
INSERT INTO PELICULA VALUES ('8', '125','PG','Jurassic World', '3','7')
INSERT INTO PELICULA VALUES ('9', '100','PG-13','Jumanji', '6','7')
INSERT INTO PELICULA VALUES ('10', '90','PG','Toy Story', '9','9')


INSERT INTO CINE VALUES ( '1','Cine Colombia','Centro Comercial Titan', '300','contacto@cinecolombia.com')
INSERT INTO CINE VALUES ( '2','Royal Films','Mall Plaza', '250','info@royalfilms.com')
INSERT INTO CINE VALUES ( '3','Procinal','Centro Comercial Gran Estación', '220','servicio@procinal.com')
INSERT INTO CINE VALUES ( '4','Cinemark','Centro Comercial Santafé', '350','soporte@cinemark.com')
INSERT INTO CINE VALUES ( '5','Cinépolis','Centro Comercial Andino', '280','contacto@cinepolis.com')
INSERT INTO CINE VALUES ( '6','Cinema Paraíso','Barrio Usaquén', '120','info@cinemaparaiso.com')
INSERT INTO CINE VALUES ( '7','Cinema VIP','Centro Comercial Multiplaza', '200','vip@cinemavip.com')
INSERT INTO CINE VALUES ( '8','Cine Star','Centro Comercial Portal 80', '180','contacto@cinestar.com')
INSERT INTO CINE VALUES ( '9','Autocinema Bogotá','Parqueadero Salitre', '150','info@autocinemabogota.com')
INSERT INTO CINE VALUES ( '10','CineMax','Centro Comercial Hayuelos', '260','soporte@cinemax.com')

SELECT *
FROM SALA

INSERT INTO SALA VALUES ( '1','Sala 1','100', '2D','1')
INSERT INTO SALA VALUES ( '2','Sala 2','80', '3D','1')
INSERT INTO SALA VALUES ( '3','Sala Premier','70', 'VIP','2')
INSERT INTO SALA VALUES ( '4','Sala 3','120', '2D','3')
INSERT INTO SALA VALUES ( '5','Sala 4','90', '3D','3')
INSERT INTO SALA VALUES ( '6','Sala IMAX','150', 'IMAX','4')
INSERT INTO SALA VALUES ( '7','Sala Deluxe','110', 'VIP','5')
INSERT INTO SALA VALUES ( '8','Sala 5','85', '2D','6')
INSERT INTO SALA VALUES ( '9','Sala 6','60', '3D','7')
INSERT INTO SALA VALUES ( '10','Sala 7','130', '2D','8')

INSERT INTO TIPO_FUNCION VALUES ('1', 'Matiné','Función temprano')
INSERT INTO TIPO_FUNCION VALUES ('2', 'Noche','Función de última hora')
INSERT INTO TIPO_FUNCION VALUES ('3', 'Tarde','Función de la tarde')
INSERT INTO TIPO_FUNCION VALUES ('4', 'Premier','Estreno especial')
INSERT INTO TIPO_FUNCION VALUES ('5', 'Función VIP','Función exclusiva premium')
INSERT INTO TIPO_FUNCION VALUES ('6', 'Función 3D','Proyección en 3D')
INSERT INTO TIPO_FUNCION VALUES ('7', 'Función IMAX','Proyección en formato IMAX')
INSERT INTO TIPO_FUNCION VALUES ('8', 'Función Doblada','Película doblada')
INSERT INTO TIPO_FUNCION VALUES ('9', 'Función Subtitulada','Película subtitulada')
INSERT INTO TIPO_FUNCION VALUES ('10', 'Maratón','Varias funciones seguidas')


INSERT INTO TIPO_ESPECTACULO VALUES ('1', 'Show Musical','Espectáculo con música en vivo')
INSERT INTO TIPO_ESPECTACULO VALUES ('2', 'Teatro','Obra teatral profesional')
INSERT INTO TIPO_ESPECTACULO VALUES ('3', 'Stand-Up Comedy','Presentación de comedia en vivo')
INSERT INTO TIPO_ESPECTACULO VALUES ('4', 'Danza','Espectáculo de baile')
INSERT INTO TIPO_ESPECTACULO VALUES ('5', 'Magia','Show de ilusionismo')
INSERT INTO TIPO_ESPECTACULO VALUES ('6', 'Circo','Actuaciones circenses')
INSERT INTO TIPO_ESPECTACULO VALUES ('7', 'Concierto Acústico','Música acústica en vivo')
INSERT INTO TIPO_ESPECTACULO VALUES ('8', 'Show Infantil','Espectáculo orientado a niños')
INSERT INTO TIPO_ESPECTACULO VALUES ('9', 'Opera','Presentación operística')
INSERT INTO TIPO_ESPECTACULO VALUES ('10', 'Performance Artístico','Arte escénico experimental')

SELECT *
FROM ESPECIALIDAD

INSERT INTO ESPECIALIDAD VALUES ('1', 'Actor')
INSERT INTO ESPECIALIDAD VALUES ('2', 'Cantante')
INSERT INTO ESPECIALIDAD VALUES ('3', 'Bailarín')
INSERT INTO ESPECIALIDAD VALUES ('4', 'Director')
INSERT INTO ESPECIALIDAD VALUES ('5', 'Productor')
INSERT INTO ESPECIALIDAD VALUES ('6', 'Guionista')
INSERT INTO ESPECIALIDAD VALUES ('7', 'Comediante')
INSERT INTO ESPECIALIDAD VALUES ('8', 'Ilusionista')
INSERT INTO ESPECIALIDAD VALUES ('9', 'Acróbata')
INSERT INTO ESPECIALIDAD VALUES ('10', 'Presentador')

INSERT INTO ARTISTA VALUES ('1','Carlos Ruiz', 'Colombiano','1')
INSERT INTO ARTISTA VALUES ('2','Ana Torres', 'Mexicana','2')
INSERT INTO ARTISTA VALUES ('3','Luis Vega', 'Argentino','3')
INSERT INTO ARTISTA VALUES ('4','María López', 'Chilena','4')
INSERT INTO ARTISTA VALUES ('5','Diego Herrera', 'Peruano','5')
INSERT INTO ARTISTA VALUES ('6','Sofía Mendes', 'Brasileña','6')
INSERT INTO ARTISTA VALUES ('7','Javier Castillo', 'Colombiano','7')
INSERT INTO ARTISTA VALUES ('8','Valentina Cruz', 'Uruguaya','8')
INSERT INTO ARTISTA VALUES ('9','Pedro Salas', 'Venezolano','9')
INSERT INTO ARTISTA VALUES ('10','Laura Medina', 'Española','10')


INSERT INTO PRODUCTOR  VALUES ('1', 'Juan Pérez','jp@correo.com')
INSERT INTO PRODUCTOR  VALUES ('2', 'Lucía Gómez','lg@correo.com')
INSERT INTO PRODUCTOR  VALUES ('3', 'Roberto Díaz','rd@correo.com')
INSERT INTO PRODUCTOR  VALUES ('4', 'Marta Sánchez','ms@correo.com')
INSERT INTO PRODUCTOR  VALUES ('5', 'Ernesto Rivas','er@correo.com')
INSERT INTO PRODUCTOR  VALUES ('6', 'Carolina Núñez','cn@correo.com')
INSERT INTO PRODUCTOR  VALUES ('7', 'Felipe Romero','fr@correo.com')
INSERT INTO PRODUCTOR  VALUES ('8', 'Daniela Cortés','dc@correo.com')
INSERT INTO PRODUCTOR  VALUES ('9', 'Andrés Molina','am@correo.com')
INSERT INTO PRODUCTOR  VALUES ('10', 'Camila Duarte','cd@correo.com')

INSERT INTO ESPECTACULO VALUES ('1','Show Latino','90.5','1')
INSERT INTO ESPECTACULO VALUES ('2','Obra Romeo y Julieta','120.0','2')
INSERT INTO ESPECTACULO VALUES ('3','Noche de Stand-Up','75.0','3')
INSERT INTO ESPECTACULO VALUES ('4','Gala de Danza Moderna','95.0','4')
INSERT INTO ESPECTACULO VALUES ('5','Magia Extrema','60.0','5')
INSERT INTO ESPECTACULO VALUES ('6','Circo Fantasía','110.0','6')
INSERT INTO ESPECTACULO VALUES ('7','Concierto Acústico','85.0','7')
INSERT INTO ESPECTACULO VALUES ('8','Show Infantil Mágico','70.0','8')
INSERT INTO ESPECTACULO VALUES ('9','Ópera Nocturna','150.0','9')
INSERT INTO ESPECTACULO VALUES ('10','Arte Experimental Vivo','65.0','10')

INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '1','1')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '2','1')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '3','2')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '4','3')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '5','3')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '6','4')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '7','5')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '8','6')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '9','7')
INSERT INTO ARTISTA_ESPECTACULO  VALUES ( '10','8')

INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '1','1')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '2','2')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '3','3')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '4','4')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '5','5')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '6','6')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '7','7')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '8','8')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '9','9')
INSERT INTO PRODUCTOR_ESPECTACULO  VALUES ( '10','10')

INSERT INTO FUNCION VALUES ('1','2025-02-10','14:00','1','1', '1','1')
INSERT INTO FUNCION VALUES ('2','2025-02-10','18:00','2','2', '2','2')
INSERT INTO FUNCION VALUES ('3','2025-02-11','16:00','3','3', '3','3')
INSERT INTO FUNCION VALUES ('4','2025-02-11','20:00','4','4', '4','4')
INSERT INTO FUNCION VALUES ('5','2025-02-12','15:30','5','5', '5','5')
INSERT INTO FUNCION VALUES ('6','2025-02-12','19:00','6','6', '6','6')
INSERT INTO FUNCION VALUES ('7','2025-02-13','13:00','7','7', '7','7')
INSERT INTO FUNCION VALUES ('8','2025-02-13','21:00','8','8', '8','8')
INSERT INTO FUNCION VALUES ('9','2025-02-14','17:00','9','9', '9','9')
INSERT INTO FUNCION VALUES ('10','2025-02-14','22:00','10','10', '10','10')

SELECT *FROM MEMBRESIA

INSERT INTO MEMBRESIA VALUES ('1','Gold','20.00','12')
INSERT INTO MEMBRESIA VALUES ('2','Silver','10.00','6')
INSERT INTO MEMBRESIA VALUES ('3','Básica','0.00','1')
INSERT INTO MEMBRESIA VALUES ('4','Platinum','30.00','24')
INSERT INTO MEMBRESIA VALUES ('5','Premium','25.00','18')
INSERT INTO MEMBRESIA VALUES ('6','Student','15.00','6')
INSERT INTO MEMBRESIA VALUES ('7','Familiar','12.00','12')
INSERT INTO MEMBRESIA VALUES ('8','VIP','35.00','12')
INSERT INTO MEMBRESIA VALUES ('9','Weekend','5.00','1')
INSERT INTO MEMBRESIA VALUES ('10','Invitado','0.00','0')

INSERT INTO CLIENTE VALUES ('1','Roberto Sánchez','robert@gmail.com','3010000000','1')
INSERT INTO CLIENTE VALUES ('2','María López','maria@gmail.com','3020000000','2')
INSERT INTO CLIENTE VALUES ('3','Juan Torres','juant@gmail.com','3030000000','3')
INSERT INTO CLIENTE VALUES ('4','Laura Martínez','lauram@gmail.com','3040000000','4')
INSERT INTO CLIENTE VALUES ('5','Pedro Gómez','pedrog@gmail.com','3050000000','5')
INSERT INTO CLIENTE VALUES ('6','Sofía Hernández','sofiah@gmail.com','3060000000','6')
INSERT INTO CLIENTE VALUES ('7','Carlos Ortiz','carloso@gmail.com','3070000000','7')
INSERT INTO CLIENTE VALUES ('8','Diana Rivas','dianar@gmail.com','3080000000','8')
INSERT INTO CLIENTE VALUES ('9','Esteban Silva','estebans@gmail.com','3090000000','9')
INSERT INTO CLIENTE VALUES ('10','Natalia Cruz','nataliac@gmail.com','3100000000','10')


SELECT *FROM BOLETO

INSERT INTO RESERVA VALUES ('1','2025-02-05','Activa','1','1')
INSERT INTO RESERVA VALUES ('2','2025-02-06','Cancelada','2','2')
INSERT INTO RESERVA VALUES ('3','2025-02-07','Activa','3','3')
INSERT INTO RESERVA VALUES ('4','2025-02-07','Activa','4','4')
INSERT INTO RESERVA VALUES ('5','2025-02-08','Pendiente','5','5')
INSERT INTO RESERVA VALUES ('6','2025-02-08','Activa','6','6')
INSERT INTO RESERVA VALUES ('7','2025-02-09','Cancelada','7','7')
INSERT INTO RESERVA VALUES ('8','2025-02-09','Activa','8','8')
INSERT INTO RESERVA VALUES ('9','2025-02-10','Pendiente','9','9')
INSERT INTO RESERVA VALUES ('10','2025-02-10','Activa','10','10')

INSERT INTO BOLETO VALUES ('1','A12','15000','1','1')
INSERT INTO BOLETO VALUES ('2','B05','18000','2','2')
INSERT INTO BOLETO VALUES ('3','C10','20000','1','3')
INSERT INTO BOLETO VALUES ('4','D03','25000','3','4')
INSERT INTO BOLETO VALUES ('5','A01','15000','1','5')
INSERT INTO BOLETO VALUES ('6','B11','18000','2','1')
INSERT INTO BOLETO VALUES ('7','C07','22000','3','2')
INSERT INTO BOLETO VALUES ('8','D15','25000','4','3')
INSERT INTO BOLETO VALUES ('9','A09','15000','1','4')
INSERT INTO BOLETO VALUES ('10','B02','18000','2','5')

INSERT INTO PROMOCION VALUES ('1','Descuento por miércoles','20.00')
INSERT INTO PROMOCION VALUES ('2','Promo estudiante','15.00')
INSERT INTO PROMOCION VALUES ('3','Promo fin de semana','10.00')
INSERT INTO PROMOCION VALUES ('4','Descuento adulto mayor','25.00')
INSERT INTO PROMOCION VALUES ('5','Combo pareja','12.00')
INSERT INTO PROMOCION VALUES ('6','Promo cumpleaños','30.00')
INSERT INTO PROMOCION VALUES ('7','Descuento primera compra','18.00')
INSERT INTO PROMOCION VALUES ('8','Promo VIP','22.00')
INSERT INTO PROMOCION VALUES ('9','Promo temporada','14.00')
INSERT INTO PROMOCION VALUES ('10','Happy hour','16.00')

SELECT *FROM BOLETO_PROMOCION

INSERT INTO BOLETO_PROMOCION VALUES ('1','1')
INSERT INTO BOLETO_PROMOCION VALUES ('2','2')
INSERT INTO BOLETO_PROMOCION VALUES ('3','3')
INSERT INTO BOLETO_PROMOCION VALUES ('4','1')
INSERT INTO BOLETO_PROMOCION VALUES ('5','4')
INSERT INTO BOLETO_PROMOCION VALUES ('6','2')
INSERT INTO BOLETO_PROMOCION VALUES ('7','5')
INSERT INTO BOLETO_PROMOCION VALUES ('8','6')
INSERT INTO BOLETO_PROMOCION VALUES ('9','1')
INSERT INTO BOLETO_PROMOCION VALUES ('10','7')
