--SENTENCIA BETWEEN
SELECT *FROM PELICULA
WHERE DURACION BETWEEN '90' AND '100'

SELECT *FROM SALA
WHERE CAPACIDAD BETWEEN '50' AND '80'


--SENTENCIA UPDATE
UPDATE ESPECTACULO 
SET NOMBRE='Show Equino' where Id_espec IN (1,3)

UPDATE ESPECTACULO 
SET Duracion='60' where Id_espec IN (1,2)


--SENTENCIA ORDER BY
SELECT *FROM MEMBRESIA
ORDER BY Descuento ASC

SELECT *FROM MEMBRESIA
ORDER BY Duracion DESC